### ISSUE TITLE
1.12.2 Server Crashes. Caused to Fluid Conduits?

### ISSUE THREAD

**Issue by Nimtrod** [SleepyTrousers/EnderIO#4597]
#### Issue Description:
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If you are using an unreleased version of Ender IO (e.g. for 1.8.9), please don't open an issue for features that have not been announced as "finished" or "working".

#### What happens:

Server crashes. And I don't know why. But in the crash report it says something about enderio so I thought i would ask here.

#### What you expected to happen:

Nothing.

#### Steps to reproduce:

I really don't know.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.12.2-5.0.22
- EnderCore: EnderCore-1.12.2-0.5.20
- Minecraft: 1.12.2
- Forge: 14.23.2.2611

#### Your most recent log file where the issue was present: 

[pastebin](https://pastebin.com/sWXhdvGQ)

**Comment by HenryLoenwind** [comment]
Interesting. A fluid conduit is connected to another fluid conduit, but that other conduit is not part of any network.

This should not be possible---while a conduit can exist without a network, it can only do so in the one tick it was placed. But for the other conduit being connected to it, the player would have to wrenched them together first...

**Comment by Nimtrod** [comment]
Okay is there anything i can else i could send you that would help?

**Comment by EpicSquid** [comment]
A photo of the set up might help

**Comment by RoboJackPlays** [comment]
Is there a way we can find the location of this setup and a way to prevent it from crashing the moment we load it in?

Btw I am the Owner of the server having the issues.

**Comment by RoboJackPlays** [comment]
Could you tell us if the crash happens on the load of the glitched setup or some sort of interaction. Would it work to look back in the logs to see what player logged in before the crash to gain the location or would that not work?

**Comment by EpicSquid** [comment]
Right yeah, the crash is happening upon loading the chunk so you won't be able to get a screen shot. I will have to look into this later today.

**Comment by RoboJackPlays** [comment]
Alright thanks :)

**Comment by broeredaan** [comment]
Hello I think I'm having this problem aswell
https://pastebin.com/6R3TTiMW
But I have no clue where its coming from or who is causing is on the server. Anything we can do to find out?

**Comment by EpicSquid** [comment]
This is hopefully fixed in the latest dev build. Please give that a try

**Comment by DEX47** [comment]
I just started getting crashes with reports containing enderio liquid conduits. The cause and behavior are completely baffling. Report as follows:

> Time: 5/3/18 1:57 PM

```
> Description: Exception in server tick loop
> 
> java.lang.NullPointerException: Exception in server tick loop
> 	at crazypants.enderio.conduits.conduit.liquid.LiquidConduit.fill(LiquidConduit.java:160)
> 	at crazypants.enderio.conduits.conduit.liquid.LiquidConduitNetwork.flowFrom(LiquidConduitNetwork.java:207)
> 	at crazypants.enderio.conduits.conduit.liquid.LiquidConduitNetwork.doFlow(LiquidConduitNetwork.java:99)
> 	at crazypants.enderio.conduits.conduit.liquid.LiquidConduitNetwork.tickEnd(LiquidConduitNetwork.java:74)
> 	at crazypants.enderio.base.handler.ServerTickHandler.onServerTick(ServerTickHandler.java:56)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_171_ServerTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:265)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
> 	at java.lang.Thread.run(Thread.java:748)
```

The crash event first happened late after everyone logged out today. I since backtracked and removed all connections to Ender I/O liquid conduits however the crash persists. The odd behavior is the crash even only happens when no one is logged into the server. I have no chunkloaders and thus haven't been able to test with that. My server has been running flawlessly in it's current revision since 4/26/18. Hopefully this is useful to you.

I am on Forge 14.23.3.2655

**Comment by EpicSquid** [comment]
@DEX47 please try the latest dev build

**Comment by Nimtrod** [comment]
We haven't had any problems since we updated to the dev build so i guess it rly has been fixed.

**Comment by EpicSquid** [comment]
Hearing that just made my day, glad it works.

**Comment by DEX47** [comment]
I have no idea where you have that download.

**Comment by DEX47** [comment]
All stable here thus far.
