### ISSUE TITLE
Loot capacitors don't show their type on server

### ISSUE THREAD

**Issue by AfterRebelion** [SleepyTrousers/EnderIO#4871]
#### Issue Description:

When looking at a loot capacitor description to see what it does on server, it doen't load well.

#### What happens:

![imagen](https://user-images.githubusercontent.com/559819/45777987-9a32d780-bc57-11e8-8a1a-b455d224aed4.png)

#### What you expected to happen:

To see all the description.

#### Steps to reproduce:

1. Make a server with EnderIO
2. Log in with a client with EnderIO
3. Search for Loot Chest (Or use "/give @p minecraft:chest 1 0 {BlockEntityTag:{LootTable:"minecraft:chests/simple_dungeon"}}" )
4. It doen't show well.
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 5.0.33
- EnderCore: 0.5.39
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.4.2760
- SpongeForge? No
- Optifine? No
- Single Player and/or Server? Server

#### Your most recent log file where the issue was present: 

Server and client log: https://gist.github.com/AfterRebelion/aa357f8a0e1c04842d94a4fec99c9c68

**Comment by tyler489** [comment]
This was fixed a while ago i'm almost certain

**Comment by AfterRebelion** [comment]
![imagen](https://user-images.githubusercontent.com/559819/67217209-a7a32e00-f424-11e9-9754-c6cf7201b7de.png)
No, it wasn't.
EnderIO 5.1.51. I know there is a 5.1.52, but the server didn't update yet. And I'm pretty sure looking at the changelog that it didn't fix this.

**Comment by tyler489** [comment]
Ah right this was that odd thing that sometimes happens with it not reading language files correctly on some servers... my mistake
